name: Production

#on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          echo ${{ secrets.MY_LINKS_AWS_ACCESS_KEY_ID }} > key.txt
          echo ${{ secrets.MY_LINKS_AWS_SECRET_ACCESS_KEY }} > secret.txt
          npm install
        env:
          CI: true
      - name: npm build
        run: |
          npm run build
        env:
          CI: true
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v2
        with:
          name: mylinks-build
          path: build
  deploy:
    name: CD part
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: ['MyLinks']
        s3-bucket: ['mylinks-codedeploy-deployments']
        s3-filename: ['mylinks-codedeploy-${{ github.sha }}']
        deploy-group: ['myLinksDeploymentGroup']
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI 2
        run: |
          echo ${{ secrets.MY_LINKS_AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.MY_LINKS_AWS_SECRET_ACCESS_KEY }}
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_LINKS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_LINKS_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: mylinks-build
          path: mylinks-build
      - name: Copy appspec.yml to build dir
        run: cp appspec.yml mylinks-build

      # Deploy push to S3
      - name: AWS Deploy push
        run: |
          SHA=${{ github.sha }}
          sed -i "s/@ver@/$SHA/g" static/js/main.*.js
          aws s3 rm s3://mylinks-codedeploy-deployments --recursive
          aws s3 cp . s3://mylinks-codedeploy-deployments --recursive
        working-directory: mylinks-build
      # Creating deployment via CodeDeploy
#      - name: Creating AWS Deployment
#        run: |
#          aws deploy create-deployment \
#          --application-name ${{ matrix.app-name }} \
#          --deployment-config-name CodeDeployDefault.AllAtOnce \
#          --deployment-group-name ${{ matrix.deploy-group }} \
#          --file-exists-behavior OVERWRITE \
#          --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \